modLoader="javafml" 
loaderVersion="[36,)"
license="All rights reserved"

[[mods]] 
modId="hyrarpg"
version="1.0" 
displayName="HyraRPG" 
logoFile="logo.png"
authors="Hyrancood" 
description='''
Special mod for Hyra-craft
Special thanks for XBLAST

Contact me: Hyrancood#5980
'''

[[dependencies.hyrarpg]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
